development:
  adapter: postgresql
  encoding: utf8
  database: wildfirecybernetics_development
  username: postgres
  password: whyme461
  host: localhost


test:
  adapter: postgresql
  encoding: utf8
  database: wildfirecybernetics_test
  username: postgres
  password: whyme461
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: wildfirecybernetics
  username: postgres
  password: whyme461
  host: localhost
